FOTSV2/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FOTSV2.Controllers
{
    public class EventsController : Controller
    {
        // GET: Event
        public ActionResult UpcomingEvents()
        {
            return View();
        }

        public ActionResult PetFest()
        {
            return View();
        }
    }


}

FOTSV2/Controllers/GetInvolvedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FOTSV2.Controllers
{
    public class GetInvolvedController : Controller
    {
        // GET: GetInvolved
        public ActionResult Membership()
        {
            return View();
        }

        public ActionResult Meetings()
        {
            return View();
        }

        public ActionResult Volunteer()
        {
            return View();
        }
    }
}

FOTSV2/Controllers/PetsForAdoptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FOTSV2.Controllers
{
    public class PetsForAdoptionController : Controller
    {
        // GET: PetsForAdoption
        public ActionResult Index()
        {
            return View();
        }
    }
}

FOTSV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Friends of the Shelter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Upcoming Events", "UpcomingEvents", "Events")</li>
                            <li>@Html.ActionLink("PetFest", "PetFest", "Events")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Fundraising", "", "Home")</li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Get Involved</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Membership", "Membership", "GetInvolved")</li>
                            <li>@Html.ActionLink("Meetings", "Meetings", "GetInvolved")</li>
                            <li>@Html.ActionLink("Volunteer", "Volunteer", "GetInvolved")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Pets for Adoption", "Contact", "PetsForAdoption")</li>
                </ul>
                 </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer-element">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h1 class="footer-title">Resources</h1>
                        <p>
                            <a class="footer-link" href="">Spay and Neuter Assistance</a> <br />
                        </p>
                        <p>
                            <a class="footer-link" href="">Paw Print Newsletter</a> <br />
                        </p>
                        <p>
                            <a class="footer-link" href="">Shelter Information</a>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h1 class="footer-title">Quick Links</h1>
                        <p>
                             <a class="footer-link" href="">Donate</a> <br />
                        </p>   
                        <p>
                            <a class="footer-link" href="">Membership</a> <br />
                        </p>
                        <p>
                            <a class="footer-link" href="">PetFest</a>
                        </p>
                       
                    </div>
                    <div class="col-md-4">
                        <h1 class="footer-title">Contact</h1>
                        <p>Friends of the Shelter, Inc</p>
                        <p>P O Box 93</p>
                        <p>Union KY 41091-0093</p>
                        <a class="phoneLink" title="Facebook" target="_blank" href="https://www.facebook.com/Friends-of-the-Shelter-Inc-SPCA-KY-227999790594908/"><img alt="Find Us On Facebook." src="~/Content/images/Facebook-32.png"> </a>

                    </div>
                </div>
            </div>
            <p>&copy; @DateTime.Now.Year - Friends of the Shelter</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>